name: Node.js CI

on:
  push:
    branches:
      - main  # Change 'main' to your default branch name if it's different
  pull_request:
    branches:
      - main  # Change 'main' to your default branch name if it's different

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.15.1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "YARN_CACHE_DIR=$(yarn cache dir)" >> $GITHUB_ENV
      
      - uses: actions/cache@v2
        with:
          path: ${{ env.YARN_CACHE_DIR }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Create config.json
        run: echo "${{ secrets.CONFIG_JSON }}" > config.json

      - name: Create firebase service account key
        run: echo "${{ secrets.FIREBASE_JSON }}" > meowd-bot-firebase-adminsdk-2g9mv-5423d91b65.json]

      - name: Install dependencies
        run: yarn install


      - name: Build
        run: yarn build
